-- exercice 1



SELECT *
FROM T_CELKO_TEN_IN_ON_TIO
WHERE SIGN(ABS(TIO_1)) + SIGN(ABS(TIO_2))
+ SIGN(ABS(TIO_3)) + SIGN(ABS(TIO_4))
+ SIGN(ABS(TIO_5)) + SIGN(ABS(TIO_6))
+ SIGN(ABS(TIO_7)) + SIGN(ABS(TIO_8))
+ SIGN(ABS(TIO_9)) + SIGN(ABS(TIO_10)) = 1;




Select * from T_CELKO_TEN_IN_ON_TIO
WHERE SIGN(ABS(TIO_1)) + SIGN(ABS(TIO_2))
+ SIGN(ABS(TIO_3)) + SIGN(ABS(TIO_4))
+ SIGN(ABS(TIO_5)) + SIGN(ABS(TIO_6))
+ SIGN(ABS(TIO_7)) + SIGN(ABS(TIO_8))
+ SIGN(ABS(TIO_9)) + SIGN(ABS(TIO_10)) = 1
AND(
CASE 
WHEN TIO_1 = 1 THEN true
WHEN TIO_2 = 1 THEN true 
WHEN TIO_3 = 1 THEN true
WHEN TIO_4 = 1 THEN true
WHEN TIO_5 = 1 THEN true 
WHEN TIO_6 = 1 THEN true 
WHEN TIO_7 = 1 THEN true 
WHEN TIO_8 = 1 THEN true
WHEN TIO_9 = 1 THEN true
ELSE false
END);

